version: "2"

services:
  master: 
    build:
      dockerfile: DockerFile.infra
      context: .
    networks:
      - mosip-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./k8s-infra:/k8s-infra
      - ./mosip-infra:/mosip-infra
  node-1: 
    build:
      dockerfile: DockerFile.infra
      context: .
    networks:
      - mosip-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./k8s-infra:/k8s-infra
      - ./mosip-infra:/mosip-infra
  node-2: 
    build:
      dockerfile: DockerFile.infra
      context: .
    networks:
      - mosip-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./k8s-infra:/k8s-infra
      - ./mosip-infra:/mosip-infra
networks:
  mosip-network: