FROM ubuntu:20.04

RUN apt-get update
RUN apt-get install -y ca-certificates curl
RUN apt-get install -y apt-transport-https
RUN curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube_latest_amd64.deb
RUN dpkg -i minikube_latest_amd64.deb

RUN apt -y install bridge-utils cpu-checker libvirt-clients libvirt-daemon qemu qemu-kvm

RUN alias kubectl="minikube kubectl -- "

CMD minikube start --driver=kvm2
