services:
  minikube: 
    build:
      dockerfile: DockerFile.ubuntu
      context: .
    ports:
      - '40193:40193'
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock