version: "2"

services:
  vm: 
      image: mosip:latest
      networks:
        - mosip-network
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ./k8s-infra:/k8s-infra
        - ./mosip-infra:/mosip-infra
  wireguard-nastion-host: 
    image: mosip:latest
    ports:
      - 51820/udp:51820/udp
    networks:
      - mosip-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  observation-cluster-nodes: 
    image: mosip:latest
    networks:
      - mosip-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  mosip-cluster-nodes: 
    image: mosip:latest
    networks:
      - mosip-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  mosip-nginx-server: 
    image: mosip:latest
    networks:
      - mosip-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
networks:
  mosip-network: